-- NFL betting tracker schema (PostgreSQL) — mirrors db/schema.sql (SQLite,
-- used for local dev) table-for-table, with every column the SQLite side
-- had to accumulate through incremental ALTER TABLE migrations already
-- folded directly into these CREATE TABLEs — a fresh Postgres database has
-- no pre-existing deployments to stay backward compatible with, so
-- backend/database.py's init_db() applies this file as-is with no
-- additive-migration step for this backend (see its DATABASE_URL branch).
--
-- Differences from the SQLite version:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY
--     ("BY DEFAULT", not "ALWAYS" — so the one-time data migration from
--     Turso can insert explicit ids to preserve existing foreign keys,
--     while ordinary app inserts that omit the id still auto-generate one
--     exactly like AUTOINCREMENT did)
-- Everything else — types, upsert syntax (ON CONFLICT ... DO UPDATE SET x =
-- EXCLUDED.x), foreign keys — is identical SQL in both engines; the app
-- never uses a SQLite-only function, so this is the only schema-level
-- porting needed.

CREATE TABLE IF NOT EXISTS games (
    game_id             TEXT PRIMARY KEY,
    season              INTEGER NOT NULL,
    week                INTEGER NOT NULL,
    game_type           TEXT NOT NULL DEFAULT 'REG',
    home_team           TEXT NOT NULL,
    away_team           TEXT NOT NULL,
    kickoff_time        TEXT,
    status              TEXT NOT NULL DEFAULT 'scheduled',
    final_home_score    INTEGER,
    final_away_score    INTEGER,
    home_spread_close   REAL,
    total_close         REAL,
    home_ml_close       INTEGER,
    away_ml_close       INTEGER,
    source              TEXT NOT NULL DEFAULT 'espn',
    stadium_id          TEXT,
    stadium             TEXT,
    roof                TEXT,
    surface             TEXT,
    home_rest           INTEGER,
    away_rest           INTEGER,
    div_game            INTEGER,
    temp                REAL,
    wind                REAL,
    precip_pct          REAL
);

CREATE INDEX IF NOT EXISTS idx_games_season_week ON games(season, week);

CREATE TABLE IF NOT EXISTS odds_snapshots (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id      TEXT NOT NULL REFERENCES games(game_id),
    provider     TEXT NOT NULL,
    captured_at  TEXT NOT NULL,
    home_spread  REAL,
    total        REAL,
    home_ml      INTEGER,
    away_ml      INTEGER
);

CREATE INDEX IF NOT EXISTS idx_odds_game ON odds_snapshots(game_id);
CREATE INDEX IF NOT EXISTS idx_odds_captured ON odds_snapshots(captured_at);

CREATE TABLE IF NOT EXISTS fpi_ratings (
    team          TEXT PRIMARY KEY,
    season        INTEGER NOT NULL,
    fpi           REAL,
    fpi_rank      INTEGER,
    off_epa       REAL,
    def_epa       REAL,
    st_epa        REAL,
    wins          INTEGER,
    losses        INTEGER,
    updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ngs_team_stats (
    season                  INTEGER NOT NULL,
    week                    INTEGER NOT NULL,
    team                    TEXT NOT NULL,
    avg_time_to_throw       REAL,
    aggressiveness          REAL,
    cpoe                    REAL,
    avg_separation          REAL,
    avg_cushion             REAL,
    yac_above_expectation   REAL,
    rush_efficiency         REAL,
    rush_yards_over_expected_per_att REAL,
    updated_at              TEXT,
    PRIMARY KEY (season, week, team)
);

CREATE TABLE IF NOT EXISTS qb_starters (
    season          INTEGER NOT NULL,
    week            INTEGER NOT NULL,
    team            TEXT NOT NULL,
    player_id       TEXT,
    player_name     TEXT NOT NULL,
    attempts        INTEGER NOT NULL,
    dropbacks       INTEGER,
    epa_dropback    REAL,
    cpoe            REAL,
    yards_per_att   REAL,
    success_rate    REAL,
    updated_at      TEXT,
    PRIMARY KEY (season, week, team)
);

CREATE TABLE IF NOT EXISTS historical_injury_counts (
    season            INTEGER NOT NULL,
    week              INTEGER NOT NULL,
    team              TEXT NOT NULL,
    impact_out_count  INTEGER NOT NULL,
    qb_listed_out     INTEGER NOT NULL,
    updated_at        TEXT,
    PRIMARY KEY (season, week, team)
);

CREATE TABLE IF NOT EXISTS rosters (
    season      INTEGER NOT NULL,
    team        TEXT NOT NULL,
    player_id   TEXT NOT NULL,
    position    TEXT,
    PRIMARY KEY (season, team, player_id)
);

CREATE INDEX IF NOT EXISTS idx_rosters_team_season ON rosters(team, season);

CREATE TABLE IF NOT EXISTS depth_chart (
    team           TEXT NOT NULL,
    position       TEXT NOT NULL,
    depth_rank     INTEGER NOT NULL,
    player_id      TEXT,
    player_name    TEXT NOT NULL,
    injury_status  TEXT,
    updated_at     TEXT NOT NULL,
    PRIMARY KEY (team, position, depth_rank)
);

CREATE INDEX IF NOT EXISTS idx_depth_chart_team ON depth_chart(team);

CREATE TABLE IF NOT EXISTS recommendation_cache (
    game_id       TEXT PRIMARY KEY,
    payload       TEXT NOT NULL,
    generated_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS news_notes (
    game_id       TEXT PRIMARY KEY,
    note          TEXT,
    generated_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS team_stats (
    season              INTEGER NOT NULL,
    week                INTEGER NOT NULL,
    team                TEXT NOT NULL,
    plays_offense       INTEGER,
    off_epa_play        REAL,
    off_epa_pass        REAL,
    off_epa_rush        REAL,
    off_success_rate    REAL,
    off_yards_play      REAL,
    pass_rate           REAL,
    def_epa_play        REAL,
    def_success_rate    REAL,
    def_yards_play      REAL,
    third_down_pct      REAL,
    third_down_pct_def  REAL,
    red_zone_td_pct     REAL,
    red_zone_td_pct_def REAL,
    turnovers_lost      INTEGER,
    turnovers_forced    INTEGER,
    turnover_margin     INTEGER,
    points_for          INTEGER,
    points_against      INTEGER,
    updated_at          TEXT,
    PRIMARY KEY (season, week, team)
);

CREATE TABLE IF NOT EXISTS users (
    user_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          TEXT NOT NULL UNIQUE,
    password_hash  TEXT NOT NULL,
    display_name   TEXT NOT NULL,
    created_at     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_favorite_teams (
    user_id     INTEGER NOT NULL REFERENCES users(user_id),
    team        TEXT NOT NULL,
    PRIMARY KEY (user_id, team)
);

CREATE TABLE IF NOT EXISTS picks (
    pick_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            INTEGER REFERENCES users(user_id),
    game_id            TEXT NOT NULL REFERENCES games(game_id),
    pick_type          TEXT NOT NULL,
    selection          TEXT NOT NULL,
    line_at_pick_time  REAL,
    stake              REAL,
    result             TEXT NOT NULL DEFAULT 'pending',
    notes              TEXT,
    created_at         TEXT NOT NULL,
    model_lean         TEXT,
    model_confidence   REAL,
    model_line         REAL,
    model_result       TEXT NOT NULL DEFAULT 'pending'
);

CREATE INDEX IF NOT EXISTS idx_picks_game ON picks(game_id);
CREATE INDEX IF NOT EXISTS idx_picks_result ON picks(result);
-- Unlike the SQLite path, this is safe to create unconditionally here: a
-- brand-new Postgres database has no pre-existing duplicate rows to choke
-- on (that dedupe-then-constrain dance in _migrate() was specifically for
-- migrating an already-populated SQLite table forward). The one-time data
-- copy from Turso (ingestion/migrate_to_postgres.py) also dedupes its
-- source rows before insert, so this holds from the first row in.
CREATE UNIQUE INDEX IF NOT EXISTS idx_picks_unique_market ON picks(user_id, game_id, pick_type);

CREATE TABLE IF NOT EXISTS qb_baseline (
    team         TEXT PRIMARY KEY,
    season       INTEGER NOT NULL,
    player_name  TEXT NOT NULL,
    updated_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS recommendation_snapshots (
    game_id    TEXT PRIMARY KEY,
    payload    TEXT NOT NULL,
    frozen_at  TEXT NOT NULL
);
